[2022-12-02T16:32:53.709+0000] {processor.py:154} INFO - Started process (PID=1867) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:32:53.710+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:32:53.711+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:32:53.711+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:32:53.718+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:32:53.716+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 8
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2022-12-02T16:32:53.719+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:32:53.739+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.038 seconds
[2022-12-02T16:33:23.861+0000] {processor.py:154} INFO - Started process (PID=1931) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:33:23.864+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:33:23.865+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:33:23.865+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:33:23.874+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:33:23.873+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 8
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2022-12-02T16:33:23.875+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:33:23.892+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.035 seconds
[2022-12-02T16:33:54.854+0000] {processor.py:154} INFO - Started process (PID=1995) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:33:54.856+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:33:54.857+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:33:54.857+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:33:54.864+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:33:54.863+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 8
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2022-12-02T16:33:54.865+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:33:54.905+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.056 seconds
[2022-12-02T16:34:25.179+0000] {processor.py:154} INFO - Started process (PID=2060) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:34:25.182+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:34:25.184+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:34:25.184+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:34:25.194+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:34:25.192+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 8
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2022-12-02T16:34:25.195+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:34:25.213+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.038 seconds
[2022-12-02T16:34:55.292+0000] {processor.py:154} INFO - Started process (PID=2122) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:34:55.294+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:34:55.295+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:34:55.295+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:34:55.301+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:34:55.300+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 8
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2022-12-02T16:34:55.302+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:34:55.313+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.023 seconds
[2022-12-02T16:35:25.392+0000] {processor.py:154} INFO - Started process (PID=2180) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:35:25.395+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:35:25.397+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:35:25.397+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:35:25.405+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:35:25.404+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 8
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2022-12-02T16:35:25.407+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:35:25.423+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.036 seconds
[2022-12-02T16:35:56.474+0000] {processor.py:154} INFO - Started process (PID=2243) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:35:56.476+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:35:56.478+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:35:56.477+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:35:56.486+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:35:56.485+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 8
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2022-12-02T16:35:56.487+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:35:56.505+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.037 seconds
[2022-12-02T16:36:27.426+0000] {processor.py:154} INFO - Started process (PID=2308) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:36:27.429+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:36:27.430+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:36:27.430+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:36:27.438+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:36:27.437+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 8
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2022-12-02T16:36:27.439+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:36:27.455+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.033 seconds
[2022-12-02T16:36:58.431+0000] {processor.py:154} INFO - Started process (PID=2372) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:36:58.434+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:36:58.436+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:36:58.436+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:36:58.443+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:36:58.442+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 8
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2022-12-02T16:36:58.445+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:36:58.462+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.036 seconds
[2022-12-02T16:37:28.744+0000] {processor.py:154} INFO - Started process (PID=2436) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:37:28.747+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:37:28.748+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:37:28.748+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:37:28.757+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:37:28.755+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 10
    from airflow import DAG
       ^
IndentationError: expected an indented block
[2022-12-02T16:37:28.758+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:37:28.772+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.032 seconds
[2022-12-02T16:37:59.139+0000] {processor.py:154} INFO - Started process (PID=2502) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:37:59.141+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:37:59.142+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:37:59.142+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:37:59.147+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:37:59.146+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 10
    from airflow import DAG
       ^
IndentationError: expected an indented block
[2022-12-02T16:37:59.148+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:37:59.163+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.026 seconds
[2022-12-02T16:38:17.351+0000] {processor.py:154} INFO - Started process (PID=2532) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:38:17.354+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:38:17.355+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:38:17.355+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:38:17.375+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:38:17.374+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:38:17.376+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:38:17.388+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.039 seconds
[2022-12-02T16:38:47.518+0000] {processor.py:154} INFO - Started process (PID=2595) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:38:47.520+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:38:47.521+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:38:47.521+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:38:47.528+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:38:47.527+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:38:47.529+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:38:47.540+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.023 seconds
[2022-12-02T16:39:07.497+0000] {processor.py:154} INFO - Started process (PID=2630) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:39:07.499+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:39:07.500+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:39:07.500+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:39:07.521+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:39:07.520+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:39:07.525+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:39:07.540+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.048 seconds
[2022-12-02T16:39:09.546+0000] {processor.py:154} INFO - Started process (PID=2631) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:39:09.548+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:39:09.549+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:39:09.549+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:39:09.569+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:39:09.567+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:39:09.570+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:39:09.583+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.040 seconds
[2022-12-02T16:39:39.695+0000] {processor.py:154} INFO - Started process (PID=2694) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:39:39.697+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:39:39.699+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:39:39.699+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:39:39.711+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:39:39.709+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:39:39.712+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:39:39.729+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.039 seconds
[2022-12-02T16:40:10.538+0000] {processor.py:154} INFO - Started process (PID=2757) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:40:10.541+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:40:10.542+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:40:10.542+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:40:10.553+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:40:10.552+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:40:10.555+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:40:10.571+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.037 seconds
[2022-12-02T16:40:41.044+0000] {processor.py:154} INFO - Started process (PID=2821) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:40:41.046+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:40:41.048+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:40:41.048+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:40:41.058+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:40:41.056+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:40:41.059+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:40:41.074+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.034 seconds
[2022-12-02T16:40:42.062+0000] {processor.py:154} INFO - Started process (PID=2822) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:40:42.064+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:40:42.065+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:40:42.065+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:40:42.085+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:40:42.083+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:40:42.086+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:40:42.096+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.037 seconds
[2022-12-02T16:41:12.440+0000] {processor.py:154} INFO - Started process (PID=2886) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:41:12.441+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:41:12.442+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:41:12.442+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:41:12.452+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:41:12.451+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:41:12.453+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:41:12.467+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.030 seconds
[2022-12-02T16:41:42.636+0000] {processor.py:154} INFO - Started process (PID=2941) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:41:42.638+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:41:42.641+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:41:42.640+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:41:42.656+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:41:42.653+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:41:42.657+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:41:42.678+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.046 seconds
[2022-12-02T16:42:12.896+0000] {processor.py:154} INFO - Started process (PID=3006) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:42:12.898+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:42:12.899+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:42:12.899+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:42:12.908+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:42:12.906+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:42:12.909+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:42:12.925+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.033 seconds
[2022-12-02T16:42:43.097+0000] {processor.py:154} INFO - Started process (PID=3070) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:42:43.099+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:42:43.101+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:42:43.101+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:42:43.122+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:42:43.117+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:42:43.123+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:42:43.141+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.052 seconds
[2022-12-02T16:43:13.579+0000] {processor.py:154} INFO - Started process (PID=3134) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:43:13.581+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:43:13.583+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:43:13.583+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:43:13.594+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:43:13.591+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:43:13.595+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:43:13.612+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.037 seconds
[2022-12-02T16:43:43.804+0000] {processor.py:154} INFO - Started process (PID=3200) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:43:43.807+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:43:43.808+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:43:43.808+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:43:43.817+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:43:43.816+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:43:43.818+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:43:43.835+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.034 seconds
[2022-12-02T16:44:14.230+0000] {processor.py:154} INFO - Started process (PID=3255) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:44:14.232+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:44:14.234+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:44:14.234+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:44:14.245+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:44:14.243+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:44:14.246+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:44:14.266+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.040 seconds
[2022-12-02T16:44:45.259+0000] {processor.py:154} INFO - Started process (PID=3318) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:44:45.263+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:44:45.264+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:44:45.264+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:44:45.278+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:44:45.276+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:44:45.279+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:44:45.297+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.042 seconds
[2022-12-02T16:45:16.228+0000] {processor.py:154} INFO - Started process (PID=3382) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:45:16.230+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:45:16.231+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:45:16.231+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:45:16.243+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:45:16.241+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:45:16.245+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:45:16.262+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.038 seconds
[2022-12-02T16:45:46.619+0000] {processor.py:154} INFO - Started process (PID=3446) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:45:46.622+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:45:46.623+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:45:46.623+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:45:46.633+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:45:46.631+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:45:46.634+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:45:46.654+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.039 seconds
[2022-12-02T16:46:16.755+0000] {processor.py:154} INFO - Started process (PID=3510) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:46:16.758+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:46:16.759+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:46:16.759+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:46:16.770+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:46:16.768+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:46:16.772+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:46:16.789+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.039 seconds
[2022-12-02T16:46:46.888+0000] {processor.py:154} INFO - Started process (PID=3574) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:46:46.890+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:46:46.892+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:46:46.892+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:46:46.908+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:46:46.904+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:46:46.911+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:46:46.936+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.052 seconds
[2022-12-02T16:47:17.127+0000] {processor.py:154} INFO - Started process (PID=3629) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:47:17.129+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:47:17.132+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:47:17.131+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:47:17.150+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:47:17.148+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:47:17.151+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:47:17.170+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.047 seconds
[2022-12-02T16:47:48.209+0000] {processor.py:154} INFO - Started process (PID=3692) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:47:48.212+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:47:48.214+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:47:48.214+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:47:48.226+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:47:48.224+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:47:48.227+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:47:48.271+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.066 seconds
[2022-12-02T16:48:19.308+0000] {processor.py:154} INFO - Started process (PID=3757) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:48:19.311+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:48:19.313+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:48:19.313+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:48:19.325+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:48:19.322+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:48:19.326+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:48:19.343+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.039 seconds
[2022-12-02T16:48:50.331+0000] {processor.py:154} INFO - Started process (PID=3821) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:48:50.333+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:48:50.334+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:48:50.334+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:48:50.346+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:48:50.343+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:48:50.348+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:48:50.365+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.039 seconds
[2022-12-02T16:49:21.206+0000] {processor.py:154} INFO - Started process (PID=3884) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:49:21.209+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:49:21.211+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:49:21.211+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:49:21.224+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:49:21.221+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:49:21.225+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:49:21.240+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.039 seconds
[2022-12-02T16:49:52.227+0000] {processor.py:154} INFO - Started process (PID=3948) to work on /opt/airflow/dags/extract.py
[2022-12-02T16:49:52.229+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T16:49:52.231+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:49:52.230+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T16:49:52.238+0000] {logging_mixin.py:120} INFO - [2022-12-02T16:49:52.236+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T16:49:52.239+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T16:49:52.253+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.028 seconds
[2022-12-02T17:01:57.849+0000] {processor.py:154} INFO - Started process (PID=4003) to work on /opt/airflow/dags/extract.py
[2022-12-02T17:01:57.859+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T17:01:57.861+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:01:57.861+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T17:01:57.871+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:01:57.868+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T17:01:57.873+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T17:01:57.938+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.116 seconds
[2022-12-02T17:02:28.875+0000] {processor.py:154} INFO - Started process (PID=4067) to work on /opt/airflow/dags/extract.py
[2022-12-02T17:02:28.877+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T17:02:28.879+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:02:28.879+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T17:02:28.898+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:02:28.895+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T17:02:28.899+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T17:02:28.940+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.071 seconds
[2022-12-02T17:02:59.996+0000] {processor.py:154} INFO - Started process (PID=4131) to work on /opt/airflow/dags/extract.py
[2022-12-02T17:03:00.000+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T17:03:00.001+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:03:00.001+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T17:03:00.012+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:03:00.009+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T17:03:00.015+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T17:03:00.034+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.044 seconds
[2022-12-02T17:03:30.937+0000] {processor.py:154} INFO - Started process (PID=4196) to work on /opt/airflow/dags/extract.py
[2022-12-02T17:03:30.938+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T17:03:30.939+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:03:30.939+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T17:03:30.947+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:03:30.945+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T17:03:30.949+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T17:03:30.963+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.030 seconds
[2022-12-02T17:08:32.325+0000] {processor.py:154} INFO - Started process (PID=4251) to work on /opt/airflow/dags/extract.py
[2022-12-02T17:08:32.327+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T17:08:32.329+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:08:32.329+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T17:08:32.339+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:08:32.337+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T17:08:32.341+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T17:08:32.360+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.040 seconds
[2022-12-02T17:09:03.407+0000] {processor.py:154} INFO - Started process (PID=4314) to work on /opt/airflow/dags/extract.py
[2022-12-02T17:09:03.409+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T17:09:03.411+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:09:03.411+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T17:09:03.420+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:09:03.418+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T17:09:03.421+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T17:09:03.451+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.047 seconds
[2022-12-02T17:09:33.512+0000] {processor.py:154} INFO - Started process (PID=4378) to work on /opt/airflow/dags/extract.py
[2022-12-02T17:09:33.516+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T17:09:33.518+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:09:33.518+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T17:09:33.530+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:09:33.528+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T17:09:33.532+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T17:09:33.551+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.044 seconds
[2022-12-02T17:10:03.801+0000] {processor.py:154} INFO - Started process (PID=4442) to work on /opt/airflow/dags/extract.py
[2022-12-02T17:10:03.804+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T17:10:03.805+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:10:03.805+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T17:10:03.813+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:10:03.811+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T17:10:03.814+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T17:10:03.831+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.034 seconds
[2022-12-02T17:10:34.050+0000] {processor.py:154} INFO - Started process (PID=4506) to work on /opt/airflow/dags/extract.py
[2022-12-02T17:10:34.053+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T17:10:34.054+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:10:34.054+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T17:10:34.063+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:10:34.061+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T17:10:34.064+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T17:10:34.091+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.045 seconds
[2022-12-02T17:11:04.275+0000] {processor.py:154} INFO - Started process (PID=4561) to work on /opt/airflow/dags/extract.py
[2022-12-02T17:11:04.279+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T17:11:04.281+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:11:04.280+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T17:11:04.297+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:11:04.293+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T17:11:04.298+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T17:11:04.323+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.053 seconds
[2022-12-02T17:28:47.843+0000] {processor.py:154} INFO - Started process (PID=4624) to work on /opt/airflow/dags/extract.py
[2022-12-02T17:28:47.846+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T17:28:47.850+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:28:47.849+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T17:28:47.891+0000] {logging_mixin.py:120} INFO - [2022-12-02T17:28:47.867+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T17:28:47.894+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T17:28:47.951+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.127 seconds
[2022-12-02T18:05:45.833+0000] {processor.py:154} INFO - Started process (PID=4687) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:05:45.834+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:05:45.836+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:05:45.835+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:05:45.842+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:05:45.840+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:05:45.843+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:05:45.859+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.037 seconds
[2022-12-02T18:16:23.865+0000] {processor.py:154} INFO - Started process (PID=4751) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:16:23.871+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:16:23.879+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:16:23.878+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:16:23.921+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:16:23.917+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:16:23.923+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:16:24.042+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.179 seconds
[2022-12-02T18:19:41.304+0000] {processor.py:154} INFO - Started process (PID=33) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:19:41.311+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:19:41.312+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:19:41.312+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:19:41.321+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:19:41.319+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:19:41.322+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:19:41.336+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.034 seconds
[2022-12-02T18:20:11.663+0000] {processor.py:154} INFO - Started process (PID=61) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:20:11.667+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:20:11.671+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:20:11.671+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:20:11.688+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:20:11.685+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:20:11.689+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:20:11.719+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.059 seconds
[2022-12-02T18:20:41.943+0000] {processor.py:154} INFO - Started process (PID=89) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:20:41.946+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:20:41.948+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:20:41.947+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:20:41.959+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:20:41.957+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:20:41.960+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:20:41.976+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.036 seconds
[2022-12-02T18:21:12.264+0000] {processor.py:154} INFO - Started process (PID=116) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:21:12.266+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:21:12.267+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:21:12.267+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:21:12.280+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:21:12.278+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:21:12.281+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:21:12.305+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.044 seconds
[2022-12-02T18:21:42.567+0000] {processor.py:154} INFO - Started process (PID=135) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:21:42.569+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:21:42.570+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:21:42.570+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:21:42.581+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:21:42.579+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:21:42.582+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:21:42.601+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.038 seconds
[2022-12-02T18:22:12.834+0000] {processor.py:154} INFO - Started process (PID=163) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:22:12.837+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:22:12.839+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:22:12.838+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:22:12.852+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:22:12.849+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:22:12.853+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:22:12.872+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.043 seconds
[2022-12-02T18:22:43.126+0000] {processor.py:154} INFO - Started process (PID=191) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:22:43.127+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:22:43.130+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:22:43.129+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:22:43.138+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:22:43.136+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:22:43.141+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:22:43.159+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.037 seconds
[2022-12-02T18:23:13.385+0000] {processor.py:154} INFO - Started process (PID=219) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:23:13.387+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:23:13.389+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:23:13.389+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:23:13.400+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:23:13.398+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:23:13.402+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:23:13.420+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.039 seconds
[2022-12-02T18:23:43.588+0000] {processor.py:154} INFO - Started process (PID=247) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:23:43.589+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:23:43.590+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:23:43.590+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:23:43.598+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:23:43.596+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:23:43.599+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:23:43.618+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.033 seconds
[2022-12-02T18:24:13.800+0000] {processor.py:154} INFO - Started process (PID=266) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:24:13.803+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:24:13.804+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:24:13.804+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:24:13.812+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:24:13.810+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:24:13.813+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:24:13.831+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.034 seconds
[2022-12-02T18:24:44.075+0000] {processor.py:154} INFO - Started process (PID=296) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:24:44.076+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:24:44.078+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:24:44.077+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:24:44.089+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:24:44.087+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:24:44.091+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:24:44.112+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.040 seconds
[2022-12-02T18:25:14.356+0000] {processor.py:154} INFO - Started process (PID=324) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:25:14.358+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:25:14.360+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:25:14.360+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:25:14.371+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:25:14.369+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:25:14.372+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:25:14.391+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.039 seconds
[2022-12-02T18:25:44.682+0000] {processor.py:154} INFO - Started process (PID=353) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:25:44.686+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:25:44.688+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:25:44.688+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:25:44.700+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:25:44.698+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:25:44.702+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:25:44.720+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.041 seconds
[2022-12-02T18:26:15.018+0000] {processor.py:154} INFO - Started process (PID=381) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:26:15.020+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:26:15.021+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:26:15.021+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:26:15.029+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:26:15.027+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:26:15.030+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:26:15.048+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.034 seconds
[2022-12-02T18:26:45.308+0000] {processor.py:154} INFO - Started process (PID=400) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:26:45.309+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:26:45.310+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:26:45.310+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:26:45.320+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:26:45.317+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:26:45.321+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:26:45.336+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.033 seconds
[2022-12-02T18:27:15.592+0000] {processor.py:154} INFO - Started process (PID=429) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:27:15.594+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:27:15.595+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:27:15.595+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:27:15.604+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:27:15.602+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:27:15.605+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:27:15.620+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.032 seconds
[2022-12-02T18:27:45.885+0000] {processor.py:154} INFO - Started process (PID=458) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:27:45.886+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:27:45.888+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:27:45.888+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:27:45.898+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:27:45.896+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:27:45.900+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:27:45.916+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.035 seconds
[2022-12-02T18:28:16.189+0000] {processor.py:154} INFO - Started process (PID=486) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:28:16.191+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:28:16.193+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:28:16.193+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:28:16.202+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:28:16.200+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:28:16.204+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:28:16.221+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.036 seconds
[2022-12-02T18:28:46.527+0000] {processor.py:154} INFO - Started process (PID=510) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:28:46.529+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:28:46.530+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:28:46.530+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:28:46.544+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:28:46.542+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:28:46.545+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:28:46.565+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.042 seconds
[2022-12-02T18:29:16.797+0000] {processor.py:154} INFO - Started process (PID=533) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:29:16.798+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:29:16.800+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:29:16.800+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:29:16.808+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:29:16.807+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:29:16.810+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:29:16.825+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.032 seconds
[2022-12-02T18:29:47.141+0000] {processor.py:154} INFO - Started process (PID=563) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:29:47.143+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:29:47.145+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:29:47.145+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:29:47.155+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:29:47.153+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/extract.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extract.py", line 2, in <module>
    from airflow.operators import BashOperator,PythonOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2022-12-02T18:29:47.157+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:29:47.172+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.034 seconds
[2022-12-02T18:30:11.408+0000] {processor.py:154} INFO - Started process (PID=581) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:30:11.411+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:30:11.413+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:30:11.413+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:30:11.481+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:30:11.636+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:30:11.636+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:extract
[2022-12-02T18:30:11.641+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:30:11.641+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:extract
[2022-12-02T18:30:11.645+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:30:11.645+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:extract
[2022-12-02T18:30:11.646+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:30:11.646+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:30:11.655+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:30:11.655+0000] {dag.py:2606} INFO - Creating ORM DAG for extract
[2022-12-02T18:30:11.662+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:30:11.662+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:30:11.446616+00:00, run_after=2022-12-03T18:30:11.446616+00:00
[2022-12-02T18:30:11.672+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.268 seconds
[2022-12-02T18:30:41.913+0000] {processor.py:154} INFO - Started process (PID=608) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:30:41.915+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:30:41.916+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:30:41.916+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:30:41.940+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:30:41.994+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:30:41.994+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:30:42.006+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:30:42.006+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:30:41.925374+00:00, run_after=2022-12-03T18:30:41.925374+00:00
[2022-12-02T18:30:42.017+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.107 seconds
[2022-12-02T18:31:12.222+0000] {processor.py:154} INFO - Started process (PID=636) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:31:12.224+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:31:12.225+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:31:12.225+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:31:12.245+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:31:12.304+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:31:12.304+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:31:12.317+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:31:12.317+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:31:12.235647+00:00, run_after=2022-12-03T18:31:12.235647+00:00
[2022-12-02T18:31:12.327+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.109 seconds
[2022-12-02T18:31:42.608+0000] {processor.py:154} INFO - Started process (PID=664) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:31:42.611+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:31:42.612+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:31:42.612+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:31:42.645+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:31:42.695+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:31:42.695+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:31:42.708+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:31:42.707+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:31:42.625198+00:00, run_after=2022-12-03T18:31:42.625198+00:00
[2022-12-02T18:31:42.718+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.115 seconds
[2022-12-02T18:32:12.961+0000] {processor.py:154} INFO - Started process (PID=691) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:32:12.964+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:32:12.965+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:32:12.965+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:32:13.008+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:32:13.061+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:32:13.060+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:32:13.074+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:32:13.074+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:32:12.982222+00:00, run_after=2022-12-03T18:32:12.982222+00:00
[2022-12-02T18:32:13.086+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.129 seconds
[2022-12-02T18:32:43.288+0000] {processor.py:154} INFO - Started process (PID=710) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:32:43.291+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:32:43.293+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:32:43.293+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:32:43.334+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:32:43.387+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:32:43.387+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:32:43.401+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:32:43.401+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:32:43.321816+00:00, run_after=2022-12-03T18:32:43.321816+00:00
[2022-12-02T18:32:43.411+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.129 seconds
[2022-12-02T18:32:49.421+0000] {processor.py:154} INFO - Started process (PID=720) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:32:49.423+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:32:49.425+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:32:49.425+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:32:49.450+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:32:49.466+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:32:49.466+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:32:49.479+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:32:49.479+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:32:49.443935+00:00, run_after=2022-12-03T18:32:49.443935+00:00
[2022-12-02T18:32:49.491+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.074 seconds
[2022-12-02T18:33:19.847+0000] {processor.py:154} INFO - Started process (PID=748) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:33:19.849+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:33:19.850+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:33:19.850+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:33:19.873+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:33:19.941+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:33:19.941+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:33:19.956+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:33:19.956+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:33:19.862913+00:00, run_after=2022-12-03T18:33:19.862913+00:00
[2022-12-02T18:33:19.967+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.125 seconds
[2022-12-02T18:33:50.155+0000] {processor.py:154} INFO - Started process (PID=775) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:33:50.157+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:33:50.158+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:33:50.158+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:33:50.177+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:33:50.241+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:33:50.240+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:33:50.255+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:33:50.255+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:33:50.167499+00:00, run_after=2022-12-03T18:33:50.167499+00:00
[2022-12-02T18:33:50.266+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.113 seconds
[2022-12-02T18:34:02.328+0000] {processor.py:154} INFO - Started process (PID=785) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:34:02.330+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:34:02.332+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:34:02.332+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:34:02.363+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:34:02.384+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:34:02.384+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:34:02.408+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:34:02.407+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:34:02.352924+00:00, run_after=2022-12-03T18:34:02.352924+00:00
[2022-12-02T18:34:02.421+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.098 seconds
[2022-12-02T18:34:32.695+0000] {processor.py:154} INFO - Started process (PID=811) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:34:32.698+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:34:32.699+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:34:32.699+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:34:32.741+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:34:32.804+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:34:32.804+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:34:32.824+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:34:32.824+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:34:32.712865+00:00, run_after=2022-12-03T18:34:32.712865+00:00
[2022-12-02T18:34:32.841+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.149 seconds
[2022-12-02T18:35:03.090+0000] {processor.py:154} INFO - Started process (PID=832) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:35:03.092+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:35:03.094+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:35:03.094+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:35:03.118+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:35:03.183+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:35:03.183+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:35:03.198+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:35:03.198+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:35:03.105473+00:00, run_after=2022-12-03T18:35:03.105473+00:00
[2022-12-02T18:35:03.210+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.123 seconds
[2022-12-02T18:35:33.451+0000] {processor.py:154} INFO - Started process (PID=861) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:35:33.454+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:35:33.455+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:35:33.455+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:35:33.488+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:35:33.538+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:35:33.538+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:35:33.559+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:35:33.559+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:35:33.476026+00:00, run_after=2022-12-03T18:35:33.476026+00:00
[2022-12-02T18:35:33.571+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.126 seconds
[2022-12-02T18:36:03.799+0000] {processor.py:154} INFO - Started process (PID=889) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:36:03.801+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:36:03.802+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:36:03.802+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:36:03.834+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:36:03.888+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:36:03.888+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:36:03.902+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:36:03.902+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:36:03.823337+00:00, run_after=2022-12-03T18:36:03.823337+00:00
[2022-12-02T18:36:03.914+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.119 seconds
[2022-12-02T18:36:34.120+0000] {processor.py:154} INFO - Started process (PID=917) to work on /opt/airflow/dags/extract.py
[2022-12-02T18:36:34.123+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/extract.py for tasks to queue
[2022-12-02T18:36:34.124+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:36:34.124+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/extract.py
[2022-12-02T18:36:34.157+0000] {processor.py:766} INFO - DAG(s) dict_keys(['extract']) retrieved from /opt/airflow/dags/extract.py
[2022-12-02T18:36:34.208+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:36:34.208+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-12-02T18:36:34.222+0000] {logging_mixin.py:120} INFO - [2022-12-02T18:36:34.222+0000] {dag.py:3340} INFO - Setting next_dagrun for extract to 2022-12-02T18:36:34.134152+00:00, run_after=2022-12-03T18:36:34.134152+00:00
[2022-12-02T18:36:34.232+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/extract.py took 0.115 seconds
